title: Brian Rojas
email: brianroj@pm.me
description: >-
  Computer Engineering & Mathematics student at UCF. 
  Specializing in security research and quantitative finance.
baseurl: ""
url: "https://brianrojrc.github.io"

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

navigation:
  - name: Home
    link: /
  - name: About
    link: /about
  - name: Projects
    link: /projects
  - name: Blog
    link: /blog
  - name: Contact
    link: /contact

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
